/* _NVRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2003-2016 by NVIDIA Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to NVIDIA
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of NVIDIA Corporation is prohibited.
 *
 * _NVRM_COPYRIGHT_END_
 */

#ifndef __ga102_dev_fifo_h__
#define __ga102_dev_fifo_h__
/* This file is autogenerated.  Do not edit */
#define NV_HOST_PFIFO_NUM_RUNLISTS 16
    #define NV_HOST_MAX_NUM_LBS 12
#endif // __ga102_dev_fifo_h__
