
#include <dev_perf_addendum.h>

#ifndef ACCESS_MAP_REGISTER
#define ACCESS_MAP_REGISTER(name) 
#endif

ACCESS_MAP_REGISTER(NV_PERF_PMASYS_CHANNEL_CONFIG_SECURE_RM(0,0))
ACCESS_MAP_REGISTER(NV_PERF_PMASYS_CHANNEL_CONFIG_USER_RM(0,0))
ACCESS_MAP_REGISTER(NV_PERF_PMASYS_CHANNEL_CONTROL_USER_RM(0,0))
ACCESS_MAP_REGISTER(NV_PERF_PMASYS_CHANNEL_MEM_BYTES_RM(0,0))
ACCESS_MAP_REGISTER(NV_PERF_PMASYS_CHANNEL_MEM_HEAD_RM(0,0))
ACCESS_MAP_REGISTER(NV_PERF_PMASYS_CHANNEL_STATUS_SECURE_RM(0,0))
ACCESS_MAP_REGISTER(NV_PERF_PMASYS_ENGINESTATUS_RM(0))
ACCESS_MAP_REGISTER(NV_PERF_PMASYS_HS_DEBUG_RM(0))
ACCESS_MAP_REGISTER(NV_PERF_PMASYS_HS_INFO_RM(0))

