
#include <dev_perf_addendum.h>

#ifndef ACCESS_MAP_REGISTER
#define ACCESS_MAP_REGISTER(name) 
#endif

ACCESS_MAP_REGISTER(NV_PERF_PMMSYSROUTER_ENGINESTATUS_RM(0))
ACCESS_MAP_REGISTER(NV_PERF_PMMSYSROUTER_GLOBAL_CNTRL_RM(0))
ACCESS_MAP_REGISTER(NV_PERF_PMMSYSROUTER_GLOBAL_PMMTRIGGERCNT_RM(0))
ACCESS_MAP_REGISTER(NV_PERF_PMMSYSROUTER_HS_CONFIG_RM(0))
ACCESS_MAP_REGISTER(NV_PERF_PMMSYSROUTER_PERFMONSTATUS_RM(0))

