/* _NVRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2003-2016 by NVIDIA Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to NVIDIA
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of NVIDIA Corporation is prohibited.
 *
 * _NVRM_COPYRIGHT_END_
 */

/* This file is autogenerated by ref2h.pl.  Do not edit */
#ifndef BOOTROM_PKC_PARAMETERS_MACRO_H
#define BOOTROM_PKC_PARAMETERS_MACRO_H

#define BMEM_STACK_START	0xF00u
#define BMEM_GLOBAL_AREA_START	BMEM_STACK_START

#define BOOTROM_GCOV_INIT	0x1
#define BOOTROM_GCOV_EXIT	0x2

#define ERROR_OK		        0x00000000u
#define ERROR_BOOTROM_START	    0x00000001
#define ERROR_INV_RANGE		    0x00000002u
#define ERROR_ALGO_DIS		    0x00000003u
#define ERROR_SIG_MISS		    0x00000004u
#define ERROR_PK_MISS		    0x00000005u
#define ERROR_SHA_BUSY		    0x00000006u
#define ERROR_SHA_ERROR		    0x00000007u
#define ERROR_PK_TAMPER		    0x00000008u
#define ERROR_SIG_WRONG		    0x00000009u
#define ERROR_ENG_NOPKC         0x0000000au
#define ERROR_EIDMSK_WRONG      0x0000000bu
#define ERROR_PARA_MISS         0x0000000cu
#define ERROR_INV_UCODID        0x0000000du
#define ERROR_INV_PKHASH        0x0000000eu
#define ERROR_PKA_ABNORMAL_STOP 0x0000000fu
#define ERROR_BOOTROM_RUNNING   0x00000010u
#define ERROR_INSTALL_SIG       0x00000011u

#define ERROR_BOOTROM_DOC_ERR   0x000000fdu
#define ERROR_BOOTROM_UNKNOW    0x000000feu
#define ERROR_BOOTROM_HANG      0x000000ffu




//LINE1 captures the position  of directChannel.c where cause the hang
//LINE2 captures the position  of bootrom_pkc.c where cause the hang
//        or if the symtom is not hang, line2 captures the position where error happened
#define NV_CMSDEC_FALCON_DEBUGINFO_ERR                          7:0
#define NV_CMSDEC_FALCON_DEBUGINFO_LINE1                       15:8
#define NV_CMSDEC_FALCON_DEBUGINFO_LINE2                      31:16

#endif
