/* _NVRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2003-2016 by NVIDIA Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to NVIDIA
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of NVIDIA Corporation is prohibited.
 *
 * _NVRM_COPYRIGHT_END_
 */

#ifndef __ga102_dev_timer_h__
#define __ga102_dev_timer_h__
/* This file is autogenerated.  Do not edit */
#define NV_PTIMER                             0x00009fff:0x00009000 /* RW--D */
#define NV_PTIMER_PRI_TIMEOUT                            0x00009080 /*       */
#define NV_PTIMER_PRI_TIMEOUT_PERIOD                           23:0 /*       */
#define NV_PTIMER_PRI_TIMEOUT_PERIOD_MIN                 0x00000003 /*       */
#define NV_PTIMER_PRI_TIMEOUT_PERIOD_MAX                 0x00ffffff /*       */
#define NV_PTIMER_PRI_TIMEOUT_PERIOD_RTL                 0x00000015 /*       */
#define NV_PTIMER_PRI_TIMEOUT_PERIOD_SHORT               0x00000006 /*       */
#define NV_PTIMER_PRI_TIMEOUT_PERIOD_INIT                0x00000100 /*       */
#define NV_PTIMER_PRI_TIMEOUT_EN                              31:31 /*       */
#define NV_PTIMER_PRI_TIMEOUT_EN_DISABLED                0x00000000 /*       */
#define NV_PTIMER_PRI_TIMEOUT_EN_ENABLED                 0x00000001 /*       */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_0                     0x00009084 /* RW-4R */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_0_TO                         0:0 /* RWXVF */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_0_TO_ERROR                   0x1 /* RW--V */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_0_TO_CLEAR                   0x0 /* -W--V */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_0_TO_NONE                    0x0 /* RW--V */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_0_WRITE                      1:1 /* RWXVF */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_0_WRITE_TRUE                 0x1 /* RW--V */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_0_WRITE_FALSE                0x0 /* RW--V */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_0_ADDR                      24:2 /* RWXVF */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_0_FECS_TGT                 31:31 /* RWXVF */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_0_FECS_TGT_TRUE              0x1 /* RW--V */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_0_FECS_TGT_FALSE             0x0 /* RW--V */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_1                     0x00009088 /* RW-4R */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_1_DATA                      31:0 /* RWXVF */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_1_DATA_WAS_READ              0x0 /* RW--V */
#define NV_PTIMER_PRI_TIMEOUT_FECS_ERRCODE               0x0000908C /* RW-4R */
#define NV_PTIMER_PRI_TIMEOUT_FECS_ERRCODE_DATA                31:0 /* RWXVF */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_3                     0x00009090 /* R--4R */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_3_SUBID                      3:0 /* R-XVF */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_3_SUBID_NONXVE_PMU    0    /*       */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_3_SUBID_NONXVE_I2C    1    /*       */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_3_SUBID_NONXVE_JTAG   2   /*       */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_3_SUBID_NONXVE_IFF    3  /*       */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_3_SUBID_NONXVE_SEC2   4    /*       */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_3_SUBID_NONXVE_GSP    5    /*       */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_3_SUBID_NONXVE_NVDEC0 6 /*       */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_3_SUBID_NONXVE_NVDEC1 7 /*       */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_3_SUBID_NONXVE_NVDEC2 12 /*       */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_3_SUBID_NONXVE_NVDEC3 14 /*       */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_3_SUBID_NONXVE_NVDEC4 15 /*       */
#define NV_PTIMER_PRI_TIMEOUT_SAVE_3_GFID                      15:8 /* R-XVF */
#define NV_PTIMER_ALARM_INTR                             0x00009140 /* RW-4R */
#define NV_PTIMER_ALARM_INTR_MASK                               0:0 /* RWIVF */
#define NV_PTIMER_ALARM_INTR_MASK_DISABLED               0x00000000 /* RWI-V */
#define NV_PTIMER_ALARM_INTR_MASK_ENABLED                0x00000001 /* RW--V */
#define NV_PTIMER_INTR_EN_0                              0x00009140 /*       */
#define NV_PTIMER_INTR_EN_0_ALARM                               0:0 /*       */
#define NV_PTIMER_INTR_EN_0_ALARM_DISABLED               0x00000000 /*       */
#define NV_PTIMER_INTR_EN_0_ALARM_ENABLED                0x00000001 /*       */
#define NV_PTIMER_INTR_EN_0_TIMER                               1:1 /*       */
#define NV_PTIMER_INTR_EN_0_TIMER_DISABLED               0x00000000 /*       */
#define NV_PTIMER_INTR_EN_0_TIMER_ENABLED                0x00000001 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK                                                                      0x00009308 /* RW-4R */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_READ_PROTECTION                                                             3:0 /* RWIVF */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_READ_PROTECTION_DEFAULT_PRIV_LEVEL   15 /* RWI-V */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED                                   0x0000000F /* RW--V */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_READ_PROTECTION_ONLY_LEVEL3_ENABLED                                  0x00000008 /* RW--V */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0                                                      0:0 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE                                        0x00000001 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE                                       0x00000000 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1                                                      1:1 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE                                        0x00000001 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE                                       0x00000000 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2                                                      2:2 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE                                        0x00000001 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE                                       0x00000000 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3                                                      3:3 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE                                        0x00000001 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE                                       0x00000000 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_WRITE_PROTECTION                                                            7:4 /* RWIVF */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_DEFAULT_PRIV_LEVEL    8 /* RWI-V */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED                                        0x0F /* RW--V */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_ONLY_LEVEL3_ENABLED                                       0x08 /* RW--V */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0                                                     4:4 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE                                       0x00000001 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE                                      0x00000000 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1                                                     5:5 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE                                       0x00000001 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE                                      0x00000000 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2                                                     6:6 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE                                       0x00000001 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE                                      0x00000000 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3                                                     7:7 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE                                       0x00000001 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE                                      0x00000000 /*       */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_READ_VIOLATION                                                              8:8 /* RWIVF */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR                                          0x00000001 /* RWI-V */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON                                            0x00000000 /* RW--V */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_WRITE_VIOLATION                                                             9:9 /* RWIVF */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR                                         0x00000001 /* RWI-V */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON                                           0x00000000 /* RW--V */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL                                                       10:10 /* RWIVF */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED                                          0x00000001 /* RWI-V */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED                                          0x00000000 /* RW--V */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL                                                      11:11 /* RWIVF */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED                                         0x00000001 /* RWI-V */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED                                         0x00000000 /* RW--V */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_SOURCE_ENABLE                                                             31:12 /* RWIVF */
#define NV_PTIMER_CFG_PRIV_LEVEL_MASK_SOURCE_ENABLE_ALL_SOURCES_ENABLED                                    0x000FFFFF /* RWI-V */
#define NV_PTIMER_TIMER_CFG0                              0x00009300 /* RW-4R */
#define NV_PTIMER_TIMER_CFG0__PRIV_LEVEL_MASK 0x00009308  /*       */
#define NV_PTIMER_TIMER_CFG0_DEN                                 4:0 /* RWIUF */
#define NV_PTIMER_TIMER_CFG0_DEN_27MHZ_REF                      0x1b /* RW--V */
#define NV_PTIMER_TIMER_CFG0_DEN_25MHZ_REF                       0x0 /* RW--V */
#define NV_PTIMER_TIMER_CFG0_DEN_108MHZ_REF                     0x1b /* RWI-V */
#define NV_PTIMER_TIMER_CFG0_DEN_100MHZ_REF                      0x0 /* RW--V */
#define NV_PTIMER_TIMER_CFG0_DEN_EMULATION                       0x0 /* RW--V */
#define NV_PTIMER_TIMER_CFG0_NUM                               18:16 /* RWIUF */
#define NV_PTIMER_TIMER_CFG0_NUM_27MHZ_REF                       0x1 /* RW--V */
#define NV_PTIMER_TIMER_CFG0_NUM_25MHZ_REF                       0x0 /* RW--V */
#define NV_PTIMER_TIMER_CFG0_NUM_108MHZ_REF                      0x7 /* RWI-V */
#define NV_PTIMER_TIMER_CFG0_NUM_100MHZ_REF                      0x0 /* RW--V */
#define NV_PTIMER_TIMER_CFG0_NUM_EMULATION                       0x0 /* RW--V */
#define NV_PTIMER_TIMER_CFG1                              0x00009304 /* RW-4R */
#define NV_PTIMER_TIMER_CFG1__PRIV_LEVEL_MASK 0x00009308  /*       */
#define NV_PTIMER_TIMER_CFG1_INTEGER                             5:0 /* RWIUF */
#define NV_PTIMER_TIMER_CFG1_INTEGER_27MHZ_REF              0x000025 /* RW--V */
#define NV_PTIMER_TIMER_CFG1_INTEGER_25MHZ_REF              0x000028 /* RW--V */
#define NV_PTIMER_TIMER_CFG1_INTEGER_108MHZ_REF             0x000009 /* RWI-V */
#define NV_PTIMER_TIMER_CFG1_INTEGER_100MHZ_REF             0x00000a /* RW--V */
#define NV_PTIMER_TIMER_CFG1_INTEGER_EMULATION              0x000002 /* RW--V */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK                                                                      0x0000948c /* RW-4R */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_READ_PROTECTION                                                             3:0 /* RWIVF */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_READ_PROTECTION_DEFAULT_PRIV_LEVEL   15 /* RWI-V */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED                                   0x0000000F /* RW--V */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_READ_PROTECTION_ONLY_LEVEL3_ENABLED                                  0x00000008 /* RW--V */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0                                                      0:0 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE                                        0x00000001 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE                                       0x00000000 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1                                                      1:1 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE                                        0x00000001 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE                                       0x00000000 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2                                                      2:2 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE                                        0x00000001 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE                                       0x00000000 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3                                                      3:3 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE                                        0x00000001 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE                                       0x00000000 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_WRITE_PROTECTION                                                            7:4 /* RWIVF */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_WRITE_PROTECTION_DEFAULT_PRIV_LEVEL  15 /* RWI-V */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED                                        0x0F /* RW--V */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_WRITE_PROTECTION_ONLY_LEVEL3_ENABLED                                       0x08 /* RW--V */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0                                                     4:4 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE                                       0x00000001 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE                                      0x00000000 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1                                                     5:5 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE                                       0x00000001 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE                                      0x00000000 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2                                                     6:6 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE                                       0x00000001 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE                                      0x00000000 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3                                                     7:7 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE                                       0x00000001 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE                                      0x00000000 /*       */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_READ_VIOLATION                                                              8:8 /* RWIVF */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR                                          0x00000001 /* RWI-V */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON                                            0x00000000 /* RW--V */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_WRITE_VIOLATION                                                             9:9 /* RWIVF */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR                                         0x00000001 /* RWI-V */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON                                           0x00000000 /* RW--V */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL                                                       10:10 /* RWIVF */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED                                          0x00000001 /* RWI-V */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED                                          0x00000000 /* RW--V */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL                                                      11:11 /* RWIVF */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED                                         0x00000001 /* RWI-V */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED                                         0x00000000 /* RW--V */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_SOURCE_ENABLE                                                             31:12 /* RWIVF */
#define NV_PTIMER_TICK_FREQ_PRIV_LEVEL_MASK_SOURCE_ENABLE_ALL_SOURCES_ENABLED                                    0x000FFFFF /* RWI-V */
#define NV_PTIMER_GR_TICK_FREQ                           0x00009480 /* RW-4R */
#define NV_PTIMER_GR_TICK_FREQ__PRIV_LEVEL_MASK 0x0000948c  /*       */
#define NV_PTIMER_GR_TICK_FREQ_SELECT                           2:0 /* RWIUF */
#define NV_PTIMER_GR_TICK_FREQ_SELECT_MAX                0x00000000 /* RW--V */
#define NV_PTIMER_GR_TICK_FREQ_SELECT_DEFAULT            0x00000005 /* RWI-V */
#define NV_PTIMER_GR_TICK_FREQ_SELECT_MIN                0x00000007 /* RW--V */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK                                                                      0x00009430 /* RW-4R */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_READ_PROTECTION                                                             3:0 /* RWIVF */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_READ_PROTECTION_DEFAULT_PRIV_LEVEL   15 /* RWI-V */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED                                   0x0000000F /* RW--V */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_READ_PROTECTION_ONLY_LEVEL3_ENABLED                                  0x00000008 /* RW--V */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0                                                      0:0 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE                                        0x00000001 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE                                       0x00000000 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1                                                      1:1 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE                                        0x00000001 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE                                       0x00000000 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2                                                      2:2 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE                                        0x00000001 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE                                       0x00000000 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3                                                      3:3 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE                                        0x00000001 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE                                       0x00000000 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_WRITE_PROTECTION                                                            7:4 /* RWIVF */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_WRITE_PROTECTION_DEFAULT_PRIV_LEVEL  15 /* RWI-V */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED                                        0x0F /* RW--V */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_WRITE_PROTECTION_ONLY_LEVEL3_ENABLED                                       0x08 /* RW--V */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0                                                     4:4 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE                                       0x00000001 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE                                      0x00000000 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1                                                     5:5 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE                                       0x00000001 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE                                      0x00000000 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2                                                     6:6 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE                                       0x00000001 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE                                      0x00000000 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3                                                     7:7 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE                                       0x00000001 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE                                      0x00000000 /*       */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_READ_VIOLATION                                                              8:8 /* RWIVF */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR                                          0x00000001 /* RWI-V */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON                                            0x00000000 /* RW--V */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_WRITE_VIOLATION                                                             9:9 /* RWIVF */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR                                         0x00000001 /* RWI-V */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON                                           0x00000000 /* RW--V */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL                                                       10:10 /* RWIVF */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED                                          0x00000001 /* RWI-V */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED                                          0x00000000 /* RW--V */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL                                                      11:11 /* RWIVF */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED                                         0x00000001 /* RWI-V */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED                                         0x00000000 /* RW--V */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_SOURCE_ENABLE                                                             31:12 /* RWIVF */
#define NV_PTIMER_TIME_PRIV_LEVEL_MASK_SOURCE_ENABLE_ALL_SOURCES_ENABLED                                    0x000FFFFF /* RWI-V */
#define NV_PTIMER_TIME_0                                 0x00009400 /* RW-4R */
#define NV_PTIMER_TIME_0__PRIV_LEVEL_MASK 0x00009430  /*       */
#define NV_PTIMER_TIME_0_NSEC                                  31:5 /* RWXUF */
#define NV_PTIMER_TIME_1                                 0x00009410 /* RW-4R */
#define NV_PTIMER_TIME_1__PRIV_LEVEL_MASK 0x00009430  /*       */
#define NV_PTIMER_TIME_1_NSEC                                  28:0 /* RWXUF */
#define NV_PTIMER_RO_TIME_0                                0x00009404 /* R--4R */
#define NV_PTIMER_RO_TIME_0_NSEC                                 31:5 /* R-XUF */
#define NV_PTIMER_RO_TIME_1                                0x00009414 /* R--4R */
#define NV_PTIMER_RO_TIME_1_NSEC                                 28:0 /* R-XUF */
#define NV_PTIMER_ALARM_0                                0x00009420 /* RW-4R */
#define NV_PTIMER_ALARM_0_NSEC                                 31:5 /* RWIUF */
#define NV_PTIMER_ALARM_0_NSEC_INIT                             0x0 /* RWI-V */
#define NV_PTIMER_TIMER_0                                0x00009428 /* RW-4R */
#define NV_PTIMER_TIMER_0_NSEC                                 31:0 /*       */
#define NV_PTIMER_TIMER_0_USEC                                31:10 /* RWIUF */
#define NV_PTIMER_TIMER_0_USEC_INIT                             0x0 /* RWI-V */
#define NV_PTIMER_VF_TIMER(i)                    (0x00009800+(i)*4) /* RW-4A */
#define NV_PTIMER_VF_TIMER__SIZE_1        64 /*       */
#define NV_PTIMER_VF_TIMER_NSEC                                31:0 /*       */
#define NV_PTIMER_VF_TIMER_USEC                               31:10 /* RWIUF */
#define NV_PTIMER_VF_TIMER_USEC_INIT                            0x0 /* RWI-V */
#define NV_PTIMER_VF_TIMER_INTR_VECTOR                   0x00009440 /* C--4R */
#define NV_PTIMER_VF_TIMER_INTR_VECTOR_ID                       7:0 /* C--VF */
#define NV_PTIMER_VF_TIMER_INTR_VECTOR_ID_VALUE  148 /* C---V */
#define NV_PTIMER_PRI_TMR_CG1                             0x00009600 /* RW-4R */
#define NV_PTIMER_PRI_TMR_CG1_MONITOR_CG_EN                      0:0 /* RWIVF */
#define NV_PTIMER_PRI_TMR_CG1_MONITOR_CG_EN_ENABLED       0x00000001 /* RW--V */
#define NV_PTIMER_PRI_TMR_CG1_MONITOR_CG_EN_DISABLED      0x00000000 /* RWI-V */
#define NV_PTIMER_PRI_TMR_CG1_MONITOR_CG_EN__PROD         0x00000000 /* RW--V */
#define NV_PTIMER_PRI_TMR_CG1_SLCG                                1:1 /* RWIVF */
#define NV_PTIMER_PRI_TMR_CG1_SLCG_ENABLED                0x00000000 /* RW--V */
#define NV_PTIMER_PRI_TMR_CG1_SLCG_DISABLED               0x00000001 /* RWI-V */
#define NV_PTIMER_PRI_TMR_CG1_SLCG__PROD                  0x00000000 /* RW--V */
#endif // __ga102_dev_timer_h__
